/*
Title: Switch User Page (Start Page) UI5 View
Author: Andrew Somerville (Capsicum Corporation) <andrew@capsicumcorp.com>
Modified: Brent Jarmaine (Capsicum Corporation) <brenton@capsicumcorp.com>
Description: Creates the page for logging in after logging out. Often used for
    switching users.
Copyright: Capsicum Corporation 2015, 2016

This file is part of iOmy.

iOmy is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

iOmy is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with iOmy.  If not, see <http://www.gnu.org/licenses/>.

*/

sap.ui.jsview("mjs.login.ForceSwitchUser", {

	/*************************************************************************************************** 
	** 1.0 - Controller Declaration
	**************************************************************************************************** 
	* Specifies the Controller belonging to this View. 
	* In the case that it is not implemented, or that "null" is returned, this View does not have a Controller.
	* @memberOf mjs.login.ForceSwitchUser
	****************************************************************************************************/ 
	getControllerName : function() {
		return "mjs.login.ForceSwitchUser";
	},

	/*************************************************************************************************** 
	** 2.0 - Content Creation
	**************************************************************************************************** 
	* Is initially called once after the Controller has been instantiated. It is the place where the UI is constructed. 
	* Since the Controller is given to this method, its event handlers can be attached right away. 
	* @memberOf mjs.login.ForceSwitchUser
	****************************************************************************************************/ 
	createContent : function(oController) {
		var me = this;
		
		//--------------------------------------------//
		//-- SwitchUser Panel						--//
		//--------------------------------------------//
		var oSwitchUserPanel = new sap.m.Panel( me.createId("oSwitchUserPanel"), {
			width: "",
			content: [] //-- Content is generated by the controller --//
		});
		
		oSwitchUserPanel.addStyleClass("TextCenter PadChildNone");
		
		
		//============================================//
		//== 1.2 - Create the Page					==//
		//============================================//
		return new sap.m.Page({
			content: [ IOMy.widgets.getNavigationalSubHeader("SWITCH USER", "", me), oSwitchUserPanel ],
			footer : IOMy.widgets.getAppFooter()
		}).setShowHeader(false).addStyleClass("MainBackground");
	}
	

});